### ISSUE TITLE
Chinese translation on opentelemetry.io website

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/docs-cn#129]
Hello @open-telemetry/docs-cn-approvers, @open-telemetry/docs-cn-maintainers,

we just launched a landing page for a Chinese translation of opentelemetry.io, https://opentelemetry.io/zh/ and we would love to have more content added there and work with you to grow this effort. Please take a look at the following discussions and issues and let us know what you think!

https://github.com/open-telemetry/opentelemetry.io/discussions/4302
https://github.com/open-telemetry/community/issues/2107
https://github.com/open-telemetry/opentelemetry.io/issues/4465

cc @open-telemetry/docs-maintainers

**Comment by steverao** [comment]
Hi everyone, my colleague and I will share a talk named [OpenTelemetry Community Update](https://kccncossaidevchn2024.sched.com/event/1eYcJ) in KubeCon HongKong in the end of August 2024. Is there anyone who will be in the conference or interested in it. We want to find a partner(Due to the limitations of rule in KubeCon, the candidate should preferably be a female and not from Alibaba) to join us talk and announce the launch of Chinese opentelemetry.io(We would like to introduce it by a slide). If you are interested or know someone who is interested, please reach out to me. Thank you very much! cc @open-telemetry/docs-cn-approvers
